# Generated by Django 5.2 on 2025-04-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration_ms',
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
