# Generated by Django 5.2 on 2025-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_track_duration_ms_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
