# Generated by Django 5.2 on 2025-04-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='Img/Album/'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='Img/Artists/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='Img/User/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='Img/Playlist/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='Img/Track/'),
        ),
    ]
