# Generated by Django 5.2 on 2025-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_image_url_alter_artists_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='Img/media/User/'),
        ),
    ]
