# Generated by Django 5.2 on 2025-05-05 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_playlist_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artists'),
        ),
        migrations.AlterField(
            model_name='track',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
